/**
 * Alert module types — HU-41 Alerta por hipoxia (SpO₂ baja).
 *
 * Defines the core domain types for the alert detection, classification,
 * and escalation system. All types are pure TypeScript — no React Native
 * or Supabase dependencies — so they can be tested in isolation.
 */

// ─── Alert Severity ──────────────────────────────────────────────

/**
 * Severity levels for health alerts (CA-04).
 * - 'advertencia': SpO₂ between warning and critical thresholds
 * - 'critica': SpO₂ below critical threshold
 */
export type AlertSeverity = 'advertencia' | 'critica';

// ─── Alert Status ────────────────────────────────────────────────

/**
 * Lifecycle states of an alert.
 * - 'activa': Alert was just generated, awaiting confirmation
 * - 'confirmada': User confirmed they received the alert
 * - 'escalada': No confirmation within 5 min, escalated to guard
 * - 'resuelta': SpO₂ returned to normal range
 */
export type AlertStatus = 'activa' | 'confirmada' | 'escalada' | 'resuelta';

// ─── Alert Type ──────────────────────────────────────────────────

/**
 * Types of vital sign alerts.
 * HU-41 implements 'hipoxia'; future HUs will add 'taquicardia',
 * 'bradicardia', 'hipertension', 'hipotension'.
 */
export type AlertType = 'hipoxia';

// ─── Threshold Configuration ─────────────────────────────────────

/**
 * Configurable thresholds for SpO₂ alert detection (CA-01).
 * All values are in percentage (0-100).
 */
export interface Spo2Thresholds {
  /** SpO₂ below this value triggers a 'advertencia' alert (default: 90%). */
  warningPercent: number;
  /** SpO₂ below this value triggers a 'critica' alert (default: 85%). */
  criticalPercent: number;
}

/** Default thresholds per spec: <90% = advertencia, <85% = crítica. */
export const DEFAULT_SPO2_THRESHOLDS: Spo2Thresholds = {
  warningPercent: 90,
  criticalPercent: 85,
};

// ─── Escalation Configuration ────────────────────────────────────

/**
 * Escalation settings (CA-05).
 * If no confirmation within `escalationTimeoutMs`, alert escalates.
 */
export interface EscalationConfig {
  /** Milliseconds to wait for user confirmation before escalating (default: 5 min). */
  escalationTimeoutMs: number;
}

/** Default: 5 minutes (300,000 ms). */
export const DEFAULT_ESCALATION_CONFIG: EscalationConfig = {
  escalationTimeoutMs: 5 * 60 * 1000,
};

// ─── Alert Record ────────────────────────────────────────────────

/**
 * A single alert instance generated by the detection engine.
 * Maps to the `alertas` table in Supabase.
 */
export interface AlertRecord {
  id: string;
  id_usuario: string;
  tipo: AlertType;
  severidad: AlertSeverity;
  status: AlertStatus;
  /** SpO₂ value that triggered the alert (percentage). */
  valor_registrado: number;
  /** Threshold that was exceeded (percentage). */
  umbral_configurado: number;
  /** ISO timestamp when the alert was generated. */
  generated_at: string;
  /** Device or source that produced the reading. */
  dispositivo_origen: string;
  /** ISO timestamp when the user confirmed the alert (null if not yet confirmed). */
  confirmed_at: string | null;
  /** ISO timestamp when the alert was escalated (null if not yet escalated). */
  escalated_at: string | null;
  /** Contact to whom the alert was escalated (null if not escalated). */
  escalated_to: string | null;
  /** ISO timestamp when the alert was resolved (SpO₂ returned to normal). */
  resolved_at: string | null;
}

/**
 * Insert payload for creating a new alert.
 * Omits server-generated fields (id, timestamps set by DB).
 */
export type AlertRecordInsert = Omit<
  AlertRecord,
  'id' | 'confirmed_at' | 'escalated_at' | 'escalated_to' | 'resolved_at'
>;

// ─── Detection Result ────────────────────────────────────────────

/**
 * Result of evaluating a SpO₂ reading against thresholds.
 * Returned by the detector — pure function, no side effects.
 */
export interface DetectionResult {
  /** Whether an alert should be generated. */
  shouldAlert: boolean;
  /** Severity of the alert (null if no alert). */
  severity: AlertSeverity | null;
  /** The threshold that was exceeded (null if no alert). */
  thresholdExceeded: number | null;
  /** Whether this is a new episode or a continuation (for dedup). */
  isNewEpisode: boolean;
}

// ─── Alert Evaluation Input ──────────────────────────────────────

/**
 * Input for the alert evaluation pipeline.
 * Contains the latest SpO₂ reading and context needed for detection.
 */
export interface Spo2EvaluationInput {
  /** Current SpO₂ percentage (0-100). */
  spo2Percent: number;
  /** User's configured thresholds (or defaults). */
  thresholds: Spo2Thresholds;
  /** Whether there was an active (unresolved) alert for this user already. */
  hasActiveAlert: boolean;
  /** Severity of the existing active alert (if any). */
  activeAlertSeverity: AlertSeverity | null;
  /** ISO timestamp of the reading. */
  readingTimestamp: string;
  /** Device/source identifier. */
  dispositivoOrigen: string;
}

// ─── Listener Types ──────────────────────────────────────────────

/**
 * Callback invoked when a new alert is generated.
 */
export type OnAlertGenerated = (alert: AlertRecord) => void;

/**
 * Callback invoked when an alert is escalated.
 */
export type OnAlertEscalated = (alert: AlertRecord) => void;

/**
 * Callback invoked when an alert is resolved.
 */
export type OnAlertResolved = (alert: AlertRecord) => void;
